apiVersion: v1
kind: Pod
metadata:
  name: pod-antiaffinity-3
  labels:
    app: pod-antiaffinity-3
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - pod-affinity-1
            - pod-affinity-2
        topologyKey: topology.kubernetes.io/zone
  containers:
  - name: nginx
    image: nginx